<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Extensoes\**" />
    <Compile Remove="RegraDeNegocio\consulta\**" />
    <EmbeddedResource Remove="Extensoes\**" />
    <EmbeddedResource Remove="RegraDeNegocio\consulta\**" />
    <None Remove="Extensoes\**" />
    <None Remove="RegraDeNegocio\consulta\**" />
    <Page Remove="Extensoes\**" />
    <Page Remove="RegraDeNegocio\consulta\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SalesGoalManager.RegraDeNegocio\SalesGoalManager.RegraDeNegocio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Imagens\5507757-200.png" />
  </ItemGroup>

</Project>
